PROFFESSIONS_EN = ["president", "vice-president", "director", "manager", "executive officer", "CEO", "deputy director",
                "managing director", "financial director", "marketing director", "general manager", "assistant manager",
                "manager", "production manager", "personnel manager", "marketing manager", "sales manager", "project manager",
                "supervisor", "inspector", "controller", "office worker", "office employee", "office clerk", "filing clerk",
                "receptionist", "secretary", "assistant", "typist", "stenographer", "banker", "bank officer", "economist",
                "auditor", "accountant", "bookkeeper", "teller", "cashier", "bank clerk", "financier", "treasurer", "investor",
                "sponsor", "stockbroker", "pawnbroker", "tax collector", "sales representative", "sales manager", "salesperson",
                "salesman", "saleswoman", "salesgirl", "salesclerk", "cashier", "seller", "buyer", "wholesale buyer", "wholesaler",
                "retailer", "merchant", "distributor", "dealer", "trader", "advertising agent", "grocer", "greengrocer", "baker",
                "butcher", "florist", "doctor", "physician", "family doctor", "general practitioner", "eye specialist",
                "ear specialist", "throat specialist", "heart specialist", "cardiologist", "surgeon", "pediatrician", "psychiatrist",
                "psychoanalyst", "dentist", "dietitian", "pharmacist", "veterinarian", "nurse", "paramedic", "nurse's aide",
                "principal", "dean", "professor", "teacher", "instructor", "schoolteacher", "college teacher", "university teacher",
                "head teacher", "senior teacher", "tutor", "mentor", "counselor", "teacher of mathematics", "mathematics teacher",
                "math teacher", "teacher of English", "history teacher", "music teacher", "student", "pupil", "learner", "scientist",
                "scholar", "researcher", "explorer", "inventor", "professor", "bachelor", "mathematician", "physicist", "chemist",
                "biologist", "botanist", "zoologist", "historian", "archaeologist", "geologist", "psychologist", "sociologist",
                "economist", "linguist", "astronomer", "philosopher", "geographer", "computer specialist", "computer programmer",
                "computer operator", "software specialist", "systems analyst", "systems administrator", "web developer",
                "web programmer", "webmaster", "web designer", "artist", "painter", "sculptor", "architect", "composer",
                "conductor", "musician", "pianist", "violinist", "guitarist", "drummer", "player", "singer", "dancer",
                "opera singer", "ballet dancer", "performer", "film director", "producer", "art director", "cameraman",
                "actor", "actress", "player", "writer", "poet", "author", "playwright", "dramatist", "scenarist", "publisher",
                "journalist", "reporter", "correspondent", "photographer", "designer", "fashion designer", "dress designer",
                "interior designer", "furniture designer", "graphic designer", "builder", "construction worker", "developer",
                "contractor", "engineer", "technician", "mechanic", "electrical engineer", "electrician", "welder", "bricklayer",
                "mason", "carpenter", "plumber", "painter", "decorator", "repairer", "repairman", "maintenance man", "handyman",
                "caretaker", "housekeeper", "cleaning lady", "cleaning woman", "janitor", "pilot", "flight engineer",
                "flight navigator", "flight attendant", "stewardess", "dispatcher", "mechanic", "car mechanic", "railroad worker",
                "railway worker", "driver", "chauffeur", "taxi driver", "cabdriver", "bus driver", "truck driver", "captain",
                "skipper", "navigator", "sailor", "judge", "lawyer", "attorney", "legal adviser", "barrister", "solicitor",
                "police officer", "policeman", "traffic officer", "detective", "guard", "bodyguard", "lifeguard", "warden",
                "prison guard", "chef", "head cook", "cook", "headwaiter", "waiter", "waitress", "bartender", "barman", "barmaid",
                "dishwasher", "busboy", "programmer"]

FANTASY_EN = ['fighter',
    'warrior',
    'soldier',
    'assassin',
    'ninja',
    'mage',
    'wizard',
    'magician',
    'archer',
    'hunter',
    'ranger',
    'berserker',
    'cleric',
    'priest',
    'enchanter',
    'necromancer',
    'shadowknight',
    'summoner',
    'dancer',
    'bard',
    'dragoon',
    'lancer',
    'knight',
    'paladin',
    'samurai',
    'warlord',
    'thief',
    'gambler',
    'pirate',
    'scout',
    'templar',
    'hero',
    'monk',
    'alchemist',
    'psychic',
    'mime',
    'gunslinger',
    'angel',
    'demon',
    'elf',
    'dwarf',
    'orc',
    'ent',
    'troll',
    'ogr',
    'vampire']

RACE_EN = ['nigger',
    'african american',
    'indian',
    'pakistani',
    'bangladeshi',
    'chinese',
    'caribbean',
    'african',
    'english',
    'welsh',
    'scottish',
    'northern irish',
    'british',
    'irish',
    'gypsy',
    'irish traveller',
    'roma',
    'arab',
    'black']

HUMANS_RU = ["мужчина", "женщина", "мальчик", "девочка", "парень", "девушка",
          "бабушка", "дедушка", "баба", "дед", "старуха", "старик", "человек"]

MIMICS_VERBS_RU = ["улыбаться", "плакать", "грустить", "расстраиваться", "удивляться", "смеяться", "веселиться", "сердиться", "хмуриться"]

WEAR_VERBS_RU = ["одеть", "надеть", "носить"]

COLORS_RU = ['красный', 'оранжевый', 'синий']
